package main

import (
	codinggo "codinggo/src"
)

func main() {
	codinggo.Program1()
	codinggo.Program2()
	codinggo.Program3()
	codinggo.Program4()
	codinggo.Program5()
	codinggo.Program6()
	codinggo.Program7()
	codinggo.Program8()
	codinggo.Program9()
	codinggo.Program10()
	codinggo.Program11()
	codinggo.Program12()
	codinggo.Program13()
	codinggo.Program14()
	codinggo.Program15()
	codinggo.Program16()
	codinggo.Program17()
	codinggo.Program18()
	codinggo.Program19()
	codinggo.Program20()
	codinggo.Program21()
	codinggo.Program22()
	codinggo.Program23()
	codinggo.Program24()
	codinggo.Program25()
	codinggo.Program26()
	codinggo.Program27()
	codinggo.Program28()
	codinggo.Program29()
	codinggo.Program30()
	codinggo.Program31()
	codinggo.Program32()
	codinggo.Program33()
	codinggo.Program34()
}
